[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Paul Watts", email = "paul.watts@me.com"},
]
dependencies = [
    "black>=22.10.0",
    "requests>=2.28.1",
]
requires-python = ">=3.11"
license = {text = "MIT"}

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool.pdm]
